[package]
name = "rust_simd"
version = "0.1.0"
authors = ["masanao.matsubara <m_matsubara@okwave.co.jp>"]
edition = "2018"

[dependencies]
bencher = "0.1.5"
rayon = "1.0"
simd = { version = "0.1.1", optional = true }

[features]
# Enable to use simd acceleration.
simd-accel = ["simd"]
